---

- name: Set up InfluxDB repository on CentOS
  when: ansible_facts['os_family'] == "RedHat"
  yum:
    name: https://dl.influxdata.com/influxdb/releases/influxdb-1.8.10-1.el7.x86_64.rpm
    state: present

- name: Install InfluxDB on CentOS
  when: ansible_facts['os_family'] == "RedHat"
  yum:
    name: influxdb
    state: present

- name: Set up InfluxDB repository on Ubuntu
  when: ansible_facts['os_family'] == "Debian"
  apt_repository:
    repo: "deb https://repos.influxdata.com/ubuntu focal stable"
    state: present

- name: Install InfluxDB on Ubuntu
  when: ansible_facts['os_family'] == "Debian"
  apt:
    name: influxdb
    update_cache: yes
    state: present

- name: Enable and start InfluxDB service
  service:
    name: influxdb
    enabled: yes
    state: started
