---

- name: Install necessary packages for Ubuntu
  when: ansible_facts['os_family'] == "Debian"
  apt:
    name:
      - wget
      - curl
      - tar
    update_cache: yes
    state: present

- name: Enable EPEL repository in CentOS
  when: ansible_facts['os_family'] == "RedHat"
  dnf:
    name: epel-release
    state: present
    
- name: Install necessary packages for CentOS
  when: ansible_facts['os_family'] == "RedHat"
  dnf:
    name:
      - wget
      - curl
      - tar
    state: present

- name: Download Prometheus tar.gz
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v2.50.0/prometheus-2.50.0.linux-amd64.tar.gz"
    dest: "/tmp/prometheus.tar.gz"

- name: Extract Prometheus binaries
  unarchive:
    src: "/tmp/prometheus.tar.gz"
    dest: /tmp/
    remote_src: yes

- name: Create a user for Prometheus
  user:
    name: prometheus
    system: yes
    shell: /bin/false

- name: Create necessary directories
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
  loop:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Move Prometheus binaries to /usr/local/bin
  command: mv /tmp/prometheus-2.50.0.linux-amd64/{{ item }} /usr/local/bin/
  with_items:
    - prometheus
    - promtool

- name: Set ownership for Prometheus binaries
  file:
    path: /usr/local/bin/{{ item }}
    owner: prometheus
    group: prometheus
  with_items:
    - prometheus
    - promtool

- name: Create Prometheus configuration file
  copy:
    dest: /etc/prometheus/prometheus.yml
    content: |
      global:
        scrape_interval: 15s
      scrape_configs:
        - job_name: 'prometheus'
          static_configs:
            - targets: ['localhost:9090']

- name: Create systemd service file for Prometheus
  copy:
    dest: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus monitoring system and time series database
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=prometheus
      Group=prometheus
      Type=simple
      ExecStart=/usr/local/bin/prometheus \
        --config.file /etc/prometheus/prometheus.yml \
        --storage.tsdb.path /var/lib/prometheus/data \

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Verify Prometheus binary and config file
  command: ls -l {{ item }}
  register: verify_files
  with_items:
    - /usr/local/bin/prometheus
    - /usr/local/bin/promtool
    - /etc/prometheus/prometheus.yml

- name: Display verification results
  debug:
    var: item
  loop: "{{ verify_files.results }}"

- name: Start and enable Prometheus service
  systemd:
    name: prometheus
    enabled: yes
    state: started
